# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroceiro',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='carroceiro',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Região onde costuma trabalhar.'),
        ),
        migrations.AlterField(
            model_name='historicalcarroceiro',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalcarroceiro',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Região onde costuma trabalhar.'),
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must have at least 8 digits and/or up to 15 digits.', regex='^\\d{8,15}$')], verbose_name='Telefone Móvel'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must have at least 8 digits and/or up to 15 digits.', regex='^\\d{8,15}$')], verbose_name='Telefone Móvel'),
        ),
    ]
